### ISSUE TITLE
Conforming to other mesh surfaces?

### ISSUE THREAD

**Issue by MostHated** [keijiro/VertexAnimationJob#1]
Hey there,
   This looks quite interesting. Do you think that this technique might be able to be used for say, creating a spell cast in which something forms on the ground and then expands, such as a mesh with an animated lava texture/shader but is able to conform to the overall shape of the surface in which it is covering? I am not pleased with the current HDRP projector/decal and have been trying to find something a bit nicer to use and something like this, if it would be able to do it fairly decently, might be what I have been looking for.

Thanks!
-MH

**Comment by keijiro** [comment]
I think it's possibly useful especially when the ground height can be easily sampled from a C# script (e.g. the ground height can be determined by raycasting with physics colliders), I think using decal is the best way in general though.

**Comment by keijiro** [comment]
I'm closing issue now. Please feel free to reopen for further problems.

**Comment by MostHated** [comment]
I was going to use a projector, but any time I try to animate it with Timeline, it seems to stop responding, even getting stuck with the texture showing on the ground after I disable it and other weird things, so I was hoping to find something a bit more reliable.
